
---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb-instances-fr
---
apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: mongodb-instances-fr
  namespace: mongodb-instances-fr
spec:
  location: francecentral
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: DatabaseAccount
metadata:
  name: micropets-db-account
  namespace: mongodb-instances-fr
spec:
  location: francecentral
  owner:
    name: mongodb-instances-fr
  kind: MongoDB
  databaseAccountOfferType: Standard
  locations:
    - locationName: francecentral
  # Optional: Save the connection details for this DatabaseAccount into a Kubernetes secret
  operatorSpec:
    secrets:
      primaryMasterKey:
        name: db-secret
        key: primarymasterkey
      secondaryMasterKey:
        name: db-secret
        key: secondarymasterkey
      documentEndpoint:
        name: db-secret
        key: endpoint
---
apiVersion: documentdb.azure.com/v1beta20210515
kind: MongodbDatabase
metadata:
  name: micropets-db
  namespace: mongodb-instances-fr
spec:
  location: francecentral
  owner:
    name: micropets-db-account
  options:
    autoscaleSettings:
      maxThroughput: 4000
  resource:
    id: micropets-db
