---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-sa-reader
  namespace: mongodb-instances-fr
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-mongodb-reading
  namespace: mongodb-instances-fr
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
    resourceNames:
      - db-secret
  - apiGroups:
      - documentdb.azure.com
    resources:
      - mongodbdatabases
    verbs:
      - get
      - list
      - watch
    resourceNames:
      - simple-mongodb-app-db
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-mongodb-reader-to-read
  namespace: mongodb-instances-fr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: azure-mongodb-reading
subjects:
  - kind: ServiceAccount
    name: mongo-sa-reader
    namespace: mongodb-instances-fr
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: mongodb-credentials-azure-exposed
  namespace: mongodb-instances-fr
spec:
  serviceAccountName: mongo-sa-reader
  inputResources:
    - name: db
      ref:
        apiVersion: documentdb.azure.com/v1beta20210515
        kind: MongodbDatabase
        name: simple-mongodb-app-db
    - name: creds
      ref:
        apiVersion: v1
        kind: Secret
        name: db-secret
  template:
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: azure-mongodb
    type: Opaque
    stringData:
      type: mongodb
      port: "10255"
      host: $(.db.spec.owner.name).mongo.cosmos.azure.com
      username: $(.db.spec.owner.name)
    data:
      password: $(.creds.data.primarymasterkey)
