name: Build Container image
env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

on:
  push:
    #branches:
    #  - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/micropets-elephants:latest
        builder: paketobuildpacks/builder:base
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.3.0
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Verify Docker image
      run: |
        docker run --rm  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} /cnb/lifecycle/detector
