apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aipets
  description: Micropets AIPETS Service
  tags:
    - web
    - tanzu
    - java    
    - ai
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/name=aipets"
spec:
  type: service
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
