apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elephants  
  description: Micropets Elephants Service
  tags:
    - web    
    - NodeJS
    - MongoDB
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/name=elephants'    
spec:
  type: service
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
