apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elephants
  description: Micropets Elephants Service
  tags:
    - web
    - tanzu
    - nodejs
    - mongodb
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/name=elephants"
spec:
  type: service
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
  dependsOn:
    - resource: default/elephants-db
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elephants-db
  description: Stores Elephants
  annotations:
    "backstage.io/techdocs-ref": dir:.
spec:
  type: database
  owner: the-pet-team
  system: micropets
