apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elephants
  description: Micropets Elephants Service
  tags:
    - web    
    - nodejs
    - mongodb
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/name=elephants"
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  lifecycle: experimental
  owner: the-pet-team
  system: micropets
  dependsOn: [Component:elephants-db]
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elephants-db
  description: Stores Elephants
  annotations:
    "backstage.io/techdocs-ref": dir:.
spec:
  type: database
  owner: the-pet-team
  system: micropets
