---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-sa-reader
  namespace: mongodb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-mongodb-role-reading
  namespace: mongodb
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - mongodbcommunity.mongodb.com
    resources:
      - mongodbcommunities
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-mongodb-reader-to-read
  namespace: mongodb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-mongodb-role-reading
subjects:
  - kind: ServiceAccount
    name: mongo-sa-reader
    namespace: mongodb
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: micropets-mongodb-k8s-credentials
  namespace: mongodb
spec:
  serviceAccountName: mongo-sa-reader
  inputResources:    
    - name: creds
      ref:
        apiVersion: v1
        kind: Secret
        name: elephants-mongodb-admin-my-user
  template:
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: k8s-mongodb
    type: Opaque
    stringData:
      type: mongodb
      port: "10255"
      options: /admin?replicaSet=elephants-mongodb&ssl=false
      host: elephants-mongodb-svc.mongodb.svc.cluster.local
    data:
      username: $(.creds.data.username)
      connectionString: $(.creds.data.connectionString\.standardSrv)
      password: $(.creds.data.password)
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretTemplate
metadata:
  name: micropets-int-mongodb-k8s-credentials
  namespace: mongodb
spec:
  serviceAccountName: mongo-sa-reader
  inputResources:    
    - name: creds
      ref:
        apiVersion: v1
        kind: Secret
        name: elephants-mongodb-admin-my-user
  template:
    metadata:
      labels:
        services.apps.tanzu.vmware.com/class: k8s-mongodb
    type: Opaque
    stringData:
      type: mongodb
      port: "10255"
      options: /admin?replicaSet=elephants-mongodb&ssl=false
      host: elephants-mongodb-svc.mongodb.svc.cluster.local
    data:
      username: $(.creds.data.username)
      connectionString: $(.creds.data.connectionString\.standardSrv)
      password: $(.creds.data.password)
      
