apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: elephants-k8s-mongodb-database
  namespace: dev-tap
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: elephants-mongodb-credentials
    namespace: mongodb # optional (if claiming across namespaces)
