apiVersion: v1
kind: Secret
metadata:
  name: secured-autfw-ui-config
stringData:
  # property-like keys; each key maps to a simple value
  type: app-configuration
  TITLE: NodeJS App with Tanzu Application Platform
  PORT: "8080"
  ENV: TAP/1.3
