apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: x-micropets-mongodb-k8s-credentials
spec:
  ref:
    apiVersion: v1
    kind: Secret
    name: micropets-mongodb-k8s-credentials
    namespace: mongodb # optional (if claiming across namespaces)
---
apiVersion: v1
kind: Secret
metadata:
  name: x-elephants-configuration
  labels:
    app.kubernetes.io/name: elephants
    app.kubernetes.io/part-of: micropets
stringData:
  # property-like keys; each key maps to a simple value
  type: app-configuration
  TITLE: Micropets NodeJS App with Tanzu Application Platform
  PORT: "8080"
  ENV: TAP/1.4
