apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: elephants-nodejs-mongodb
  namespace: micropets-int
  annotations:
    autoscaling.knative.dev/minScale: "1"
  labels:    
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/name: elephants
    app.kubernetes.io/part-of: micropets-app
    micropets/kind: backend
spec:
  serviceAccountName: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/micropets-elephants
      ref:
        branch: main
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: v1
        kind: Secret
        name: elephants-configuration
    - name: mongodb-database
      ref:
        apiVersion: v1
        kind: Secret
        name: micropets-int-mongodb-k8s-credentials
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: skip-test
