apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: elephants
  annotations:
    serviceclaims.supplychain.apps.x-tanzu.vmware.com/extensions: '{"kind":"ServiceClaimsExtension","apiVersion":"supplychain.apps.x-tanzu.vmware.com/v1alpha1","spec":{"serviceClaims":{"mongodb-database-not-used":{"namespace":"mongodb"}}}}'
  labels:
    apps.tanzu.vmware.com/workload-type-x: custom-server
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: elephants
    micropets/kind: backend
spec:
  serviceAccount: tap-default
  source:
    git:
      url: https://github.com/bmoussaud/micropets-elephants
      ref:
        branch: main
  serviceClaims:
    - name: app-config
      ref:
        apiVersion: v1
        kind: Secret
        name: elephants-configuration
    - name: mongodb-database
      ref:
        apiVersion: v1
        kind: Secret
        name: elephants-mongodb-credentials
  params:
    - name: fqdn
      value: www.dev-tap.tap3.eu.aks.mytanzu.xyz
    - name: prefix
      value: my-custom-prefix
    - name: gitops_server_address
      value: https://github.com/
    - name: gitops_repository_owner
      value: bmoussaud
    - name: gitops_repository_name
      value: micropets-app-gitops
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
